name: test_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: 0.4.3+1
  firebase_auth: 0.15.3
  cupertino_icons: ^0.1.2

dev_dependencies:
  mockito: 4.1.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/background_sky.jpeg
    - assets/lang/en.json
    - assets/lang/de.json